# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 杨挺的文档仓库  # 博客标题
email: ytating@foxmail.com # 你的邮箱
description: >
  文档，代码，教程，心得…………    
logo: "assets/images/logo.jpg"    #自定义 logo
baseurl: "/ytating" # 重要：如果你绑定了自定义域名或使用了自己的用户名作为项目名，请删除本行并修改下一行
url: "http://yourdomain.com" # 如果你绑定了自定义域名或使用了自己的用户名作为项目名，请修改本行为你的域名
paginate:	10 # 每页显示文章数量

name: '挺Joe'   # 你的昵称
bio: >
  GIT TEST  
author_image: "/assets/images/author.jpg"  #个人头像
twitter_username: ytating
github_username:  ytating1
coding_username: ytating  # 你的 Coding.net 用户名

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
